name: Compilar APK REPL4Y

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Java JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Recriar Wrapper e Compilar APK
        run: |
          # 1. Instala o gradle padrão do sistema
          sudo apt-get update && sudo apt-get install -y gradle
          
          # 2. Gera a pasta gradle/wrapper e o arquivo .jar que faltaram
          gradle wrapper
          
          # 3. Dá permissão e compila o projeto
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Disponibilizar Link de Download do APK
        uses: actions/upload-artifact@v4
        with:
          name: REPL4Y-TV-Instalador
          path: "app/build/outputs/apk/**/*.apk"
          retention-days: 14
