name: Compilar APK REPL4Y

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Java JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permissao de execucao ao Gradle
        run: chmod +x gradlew

      - name: Compilar APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Disponibilizar Link de Download do APK
        uses: actions/upload-artifact@v4
        with:
          name: REPL4Y-TV-Instalador
          path: "app/build/outputs/apk/**/*.apk"
          retention-days: 14
